//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtherCAT {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtherCAT.NET.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EtherCAT configuration does not match the actual one. Consider reloading the terminals. ähnelt.
        /// </summary>
        internal static string EthercatGateway_EtherCATConfigurationMismatch {
            get {
                return ResourceManager.GetString("EthercatGateway_EtherCATConfigurationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The SlaveInfo set is invalid: A SlaveInfo ID must be unique. ähnelt.
        /// </summary>
        internal static string EthercatSettings_SlaveInfoIdNotUnique {
            get {
                return ResourceManager.GetString("EthercatSettings_SlaveInfoIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The working counter is 0 (SOEM). ähnelt.
        /// </summary>
        internal static string Native_0x0000 {
            get {
                return ResourceManager.GetString("Native_0x0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sent frame did not return within the specified timeout (SOEM). ähnelt.
        /// </summary>
        internal static string Native_0x0001 {
            get {
                return ResourceManager.GetString("Native_0x0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown frame was received (SOEM). ähnelt.
        /// </summary>
        internal static string Native_0x0002 {
            get {
                return ResourceManager.GetString("Native_0x0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A general error occured (SOEM). ähnelt.
        /// </summary>
        internal static string Native_0x0003 {
            get {
                return ResourceManager.GetString("Native_0x0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ScanDevices() ähnelt.
        /// </summary>
        internal static string Native_0x0100 {
            get {
                return ResourceManager.GetString("Native_0x0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The adapter could not be initialized. Possible reasons are:
        ///
        ///Windows: 
        ///- WinPcap is not installed
        ///- network interface is disabled
        ///- TwinCAT blocks the network interface
        ///
        ///Linux: 
        ///- The application is not running as root. ähnelt.
        /// </summary>
        internal static string Native_0x0101 {
            get {
                return ResourceManager.GetString("Native_0x0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not disable process data watchdog. ähnelt.
        /// </summary>
        internal static string Native_0x0102 {
            get {
                return ResourceManager.GetString("Native_0x0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not detect any slaves. On Windows, a possible cause is a running TwinCAT instance which blocks the network interface. ähnelt.
        /// </summary>
        internal static string Native_0x0103 {
            get {
                return ResourceManager.GetString("Native_0x0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfigureIoMap() ähnelt.
        /// </summary>
        internal static string Native_0x0200 {
            get {
                return ResourceManager.GetString("Native_0x0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfigureDc() ähnelt.
        /// </summary>
        internal static string Native_0x0300 {
            get {
                return ResourceManager.GetString("Native_0x0300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No slave supports distributed clocks. ähnelt.
        /// </summary>
        internal static string Native_0x0301 {
            get {
                return ResourceManager.GetString("Native_0x0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The static drift compensation for distributed clocks failed. Consider increasing the TargetTimeDifference in the EcSettings object. ähnelt.
        /// </summary>
        internal static string Native_0x0302 {
            get {
                return ResourceManager.GetString("Native_0x0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfigureSync01() ähnelt.
        /// </summary>
        internal static string Native_0x0400 {
            get {
                return ResourceManager.GetString("Native_0x0400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The AssignActivate byte length is invalid. ähnelt.
        /// </summary>
        internal static string Native_0x0401 {
            get {
                return ResourceManager.GetString("Native_0x0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not implemented. ähnelt.
        /// </summary>
        internal static string Native_0x0402 {
            get {
                return ResourceManager.GetString("Native_0x0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RequestSafeOpState() ähnelt.
        /// </summary>
        internal static string Native_0x0500 {
            get {
                return ResourceManager.GetString("Native_0x0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more terminals did not reach SafeOp-state. ähnelt.
        /// </summary>
        internal static string Native_0x0501 {
            get {
                return ResourceManager.GetString("Native_0x0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RequestOpState() ähnelt.
        /// </summary>
        internal static string Native_0x0600 {
            get {
                return ResourceManager.GetString("Native_0x0600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more terminals did not reach Op-state. This may happen due to lost frames. ähnelt.
        /// </summary>
        internal static string Native_0x0601 {
            get {
                return ResourceManager.GetString("Native_0x0601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UpdateIo() ähnelt.
        /// </summary>
        internal static string Native_0x0700 {
            get {
                return ResourceManager.GetString("Native_0x0700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CompensateDcDrift() ähnelt.
        /// </summary>
        internal static string Native_0x0800 {
            get {
                return ResourceManager.GetString("Native_0x0800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ReadSlaveState() ähnelt.
        /// </summary>
        internal static string Native_0x0900 {
            get {
                return ResourceManager.GetString("Native_0x0900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SdoWrite() ähnelt.
        /// </summary>
        internal static string Native_0x0A00 {
            get {
                return ResourceManager.GetString("Native_0x0A00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The slave has no mailbox. ähnelt.
        /// </summary>
        internal static string Native_0x0A01 {
            get {
                return ResourceManager.GetString("Native_0x0A01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UploadPdoConfig() ähnelt.
        /// </summary>
        internal static string Native_0x0B00 {
            get {
                return ResourceManager.GetString("Native_0x0B00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read SM PDO assign register entry (number of PDOs). ähnelt.
        /// </summary>
        internal static string Native_0x0B01 {
            get {
                return ResourceManager.GetString("Native_0x0B01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read SM PDO assign register entries (PDO indices). ähnelt.
        /// </summary>
        internal static string Native_0x0B02 {
            get {
                return ResourceManager.GetString("Native_0x0B02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read PDO config register entry (number of SDOs / variables). ähnelt.
        /// </summary>
        internal static string Native_0x0B03 {
            get {
                return ResourceManager.GetString("Native_0x0B03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read PDO config register entries (SDO / variable indices). ähnelt.
        /// </summary>
        internal static string Native_0x0B04 {
            get {
                return ResourceManager.GetString("Native_0x0B04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [error messages of private functions] ähnelt.
        /// </summary>
        internal static string Native_0xF000 {
            get {
                return ResourceManager.GetString("Native_0xF000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation of the configured station alias failed. ähnelt.
        /// </summary>
        internal static string Native_0xF001 {
            get {
                return ResourceManager.GetString("Native_0xF001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UnknownErrorCode ähnelt.
        /// </summary>
        internal static string Native_0xFFFF {
            get {
                return ResourceManager.GetString("Native_0xFFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ID must be greater zero. ähnelt.
        /// </summary>
        internal static string SlaveInfo_IdInvalid {
            get {
                return ResourceManager.GetString("SlaveInfo_IdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified network interface could not be found. ähnelt.
        /// </summary>
        internal static string SoemWrapper_NetworkInterfaceNotFound {
            get {
                return ResourceManager.GetString("SoemWrapper_NetworkInterfaceNotFound", resourceCulture);
            }
        }
    }
}
